### PR TITLE
merge dev-2022

### PR DESCRIPTION
**Pull request by FecoDoo**
issues fixed:
- [X] compatibility issues with nbconvert v6.x
- [X] jinja template searching path (mathjax URL)
- [X] deprecated function calls
- [X] inconsistent behaviors of Selenium send_keys() when dealing with [datetime-local](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local) field among various system settings

### CODE REVIEW

**Comment by rkdarst** [comment]
Great work!  I resolved a conflict to see about the tests.

But I wouldn't merge this as it is: we shouldn't add any commits to our 'master' branch (it should directly follow the upstream, nothing new in our 'master'.  We shouldn't really use it for anything, for that matter).  And this series of commits has some Aalto-specific version number increases.

I can take and clean this up onto a single branch which is ready to merge upstream.  Maybe it would be good for me to do this and others to watch, since all this cherry picking can be complex and hard to start with?

**Comment by FecoDoo** [comment]
> Great work! I resolved a conflict to see about the tests.
> 
> But I wouldn't merge this as it is: we shouldn't add any commits to our 'master' branch (it should directly follow the upstream, nothing new in our 'master'. We shouldn't really use it for anything, for that matter). And this series of commits has some Aalto-specific version number increases.
> 
> I can take and clean this up onto a single branch which is ready to merge upstream. Maybe it would be good for me to do this and others to watch, since all this cherry picking can be complex and hard to start with?

Thanks! I think it would be a good idea that you to take over from here. I will keep looking and help if any explanation is needed.

**Comment by FecoDoo** [comment]
sorry for the misclick

**Comment by rkdarst** [comment]
This is done, it seems!  Different PR, but by working together someone was able to do it.  I'll close this to keep things clean.

Thanks for your work on this!

**Pull request closed without merging**
